name: persian_localizer
description: A CLI tool to extract and localize Persian strings in Dart/Flutter projects
version: 0.1.0
homepage: https://github.com/AmirrezaSedghamiz/Persian-Localization-Tool-For-Flutter.git

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  analyzer: ^5.0.0
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0

executables:
  persian_localizer: